name             'jenkins-docker-cookbook'
maintainer       'Sungho Park'
maintainer_email 'spark@codesconsulting.com'
license          'All rights reserved'
description      'Cookbook to bring up dockerized jenkins'
long_description 'Cookbook to bring up dockerized jenkins'
version          '0.1.0'
depends 'docker', '~> 2.0'
